### PR TITLE
Update user.js

### PR DESCRIPTION
**Pull request by Romanior**
fix types.identifier() invoking as function

### CODE REVIEW

**Comment by alexvcasillas** [comment]
Thanks for this PR! :)
Is there any other dependency you'd like to update also? 🙃

**Comment by Romanior** [comment]
```
    "mobx": "^5.9.4",
    "mobx-react": "^5.4.4",
    "mobx-state-tree": "^3.14.0",
```
could also work.

**Comment by alexvcasillas** [comment]
Feel free to update as many dependencies as you wish in this PR :)

**Comment by Romanior** [comment]
closing in favour of https://github.com/alexvcasillas/react-mobx-router/pull/7

**Pull request closed without merging**
